// FFCC history, verbatim from faithfellowshiplive.org (Our History page,
// archived 2024-06-16). The text was written around 2016 and has not been
// updated since. See CONTENT_TODO.md.

export const history = {
  heading: "History of Faith Fellowship Community Church",
  source: "https://faithfellowshiplive.org/about/our-identity/our-history/",
  paragraphs: [
    "On November 5, 2000, Faith Fellowship Community Church held its first Order of Worship at the North Highlands Community Center, with a powerful Word from God delivered by Rev. Rosalee Charley. Although November 5, 2000, is the date that we mark as the birth date of the church, the history of what we now know as one of the most loving, dynamic, faith-filled church families in Sacramento, actually started two months earlier.",
    "On September 1, 2000, a small group of believers, who felt that they were being led by God to do a new, different work in the community, held a meeting at the home of Bill & Yvonne Miller. After Bro. Miller conducted a Bible Study, Willie Register facilitated the meeting, which was attended by Sylvia Jackson, Iveda Thomas, Charlotte McBride, Yvonne Miller, Deacon Leo Hart, Deacon James Jefferson, Jim & Bonnie Oliver, Dave & Barbara Gordon, Georgetta Coleman, Priscilla Marsh, Yvonne Littleton, Charles & Eva Young, Rev. Rosalee Charley, Pearl Register, Ron & Alicia Cross, Deborah VanDunk, and Mother Helena Robinson. All were part of the first building blocks of what would soon be known as Faith Fellowship Community Church.",
    "A second meeting was held on September 23, 2000, to discuss how to proceed with the call of God to start the church. The people who attended the first meeting were joined at this follow up meeting by Charlene Johnson, Lawrence & Karen Bodie, Dorothy Horne, Betty Moore, Arlene Collins, Yvonne Walden, Carrie Denson, Lovette Broussard, Ernest Smith, Dorothy Miles, Mai-Gemu & Joy Johnson, Susan Kohler, Anthony Sims, and Derrick & Love Miller. This was the meeting in which research was conducted on bylaws, on church formation as a non-profit organization, and on church incorporation.",
    "As time progressed and additional meetings were held, the need to move to a facility that could accommodate the ever growing group became evident. Dr. Joy Johnson and Bro. Dave Gordon sought to find a meeting location that was suitable for all who were interested in attending these sessions. As a result of Dr. Johnson and Dave Gordon’s diligent effort, on October 25, 2000, one hundred and six (106) believers gathered at the North Highlands Community Center for Bible Study taught by Dr. Johnson. This study time concluded with prayers, songs of praise, and a plan for the first Worship Service.",
    "A Steering Team was organized by Willie Register to formalize the body of believers. Dave Gordon, Priscilla Marsh, and Phyllis Burch, were appointed as the Finance Team. In addition, there were four deacons, five ministers, a number of trustees and ushers, and a full music ministry, who were all ready, willing, and able to serve. A group of dedicated volunteers led by Oliver & Seal Cayasso delivered and set up chairs at the Community Center so that adequate seating would be available to our congregants. The efforts of these founding members will be thankfully remembered forever.",
    "It was soon agreed by the congregation that the church would be Bible-based and Christ-Centered, and Rev. Rosalee Charley was asked to serve as Interim Pastor. On December 3, 2000, Deacon Leon Archie taught the first Sunday School lesson to a general assembly of eighty-eight (88). On December 10, 2000, the church body selected the name of “Faith Fellowship Community Church.” Bro. Heyman Matlock and others filed the Secretary of State papers, and an Incorporation Service was held on Sunday, December 24, 2000, with Dr. Ronn Elmore as the guest speaker.",
    "After bringing the Word to the Faith Fellowship family in December 2000, Dr. Ronn Elmore became a vital resource for the church as we began seeking a pastor. Dr. Ronn offered his support, guidance, and direction on various aspects of church development, and on identifying the one who God would call to lead us. Over time, it became clear that Dr. Ronn was God’s choice for Pastor of Faith Fellowship, and on December 6, 2001, the church heard from God and confirmed that Dr. Ronn Elmore would be installed as Pastor on January 20, 2002.",
    "Under the leadership of Dr. Ronn Elmore, on April 12, 2003, Faith Fellowship took possession of our current home, at 5937 Watt Avenue, in North Highlands, California. In addition, Dr. Elmore launched fundraising efforts for victims of Hurricane Katrina and the tsunami in Thailand, spear-headed mission trips to El Doret, Kenya, and introduced the “Purpose Driven Church” concept to Faith Fellowship, which resulted in the formation of many home-groups.",
    "After many years of shepherding the Faith Fellowship flock, Dr. Ronn heard God’s call to make way for new leadership. Dr. Joy Johnson served briefly as Interim Pastor, and then Rev. Rosalee Charley stepped into the role once again.",
    "Between November 2007, and January 2016, Faith Fellowship was served by Pastor Dwight L. Ford for a brief period of time, by Interim Pastor Rosalee Charley, by Pastor David Arthur, for just over four (4) years, and again by Rosalee Charley, for the greater part of 2015. It was during this season that Interim Pastor Charley reminded us of God’s commitment to Faith Fellowship, that He would never leave us nor forsake us.",
    "And in keeping with His faithfulness and the favor that God has demonstrated toward Faith Fellowship time and again, the Lord moved once again on behalf of Faith Fellowship in July 2015, and led Dr. Melvin G. Barney, Esq., to leave his church and law practice in Southern California, and return to Faith Fellowship. Dr. Barney had worked in ministry along side Dr. Ronn Elmore at Faith Fellowship between 2002 and 2004, as an Associate Pastor, and as a member of the church’s strategic planning team. During the time he was away, Dr. Barney obtained a Doctorate in Ministry, and nearly six (6) years of pastoral experience, which we now know, were preparation for the call to serve as the next Pastor of Faith Fellowship Community Church.",
    "On January 17, 2016, just six months after his return, Dr. Melvin G. Barney, Esq., was installed by Dr. Ronn Elmore, as Senior Pastor of Faith Fellowship Community Church.",
    "Within his first month as our pastor, Dr. Barney introduced us to his doctoral dissertation, the “Eight Weeks of Healing” Initiative, which was designed to guide a new pastor in the resuscitation and healing of a church that has been through trauma. Now that the church has been healed, we are pioneering Pastor Barney’s vision for creating “The Ultimate Worship Experience!” at Faith Fellowship, where we prioritize and pursue accurate division of God’s Word, effective prayer, praise and worship that touches the heart of God, and faith that pleases God.",
    "We are Faith Fellowship Community Church. We have come this far by faith, and we will continue to stand on God’s promises that our church family will continue to make our name, Faith Fellowship, a living testimony.",
  ],
} as const;
